# Generated by Django 5.2.12 on 2026-03-06 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgaps_creation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='learning_outcome',
            field=models.TextField(blank=True, help_text='What students will understand or be able to do after this topic.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='planned_hours',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Total planned teaching hours for this topic.', max_digits=4),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'COORDINATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
