# Generated by Django 5.2.12 on 2026-03-06 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('kgaps_creation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_handled', models.DecimalField(decimal_places=1, max_digits=4)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_auto_generated', models.BooleanField(default=False, help_text='True when created automatically from a DailyEntry.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlings', to='courses.courseassignment')),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='topic_handlings', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlings', to='kgaps_creation.topic')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HandlingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_verifications', to=settings.AUTH_USER_MODEL)),
                ('handling', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='kgaps_handling.topichandling')),
            ],
        ),
    ]
