# Generated by Django 5.2.12 on 2026-03-06 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_domain'),
        ('kgaps_handling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sheet_url', models.URLField()),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of students who submitted / completed this assignment.', max_digits=5)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time the completion % was recalculated from the sheet.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_trackers', to='courses.courseassignment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_sheet_url', models.URLField(help_text='Link to the uploaded result sheet.')),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of students who passed this course.', max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='courses.courseassignment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
