# Generated by Django 5.2.12 on 2026-03-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('kgaps_creation', '0002_topic_learning_outcome_topic_planned_hours_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='kgaps_creation.domain'),
        ),
    ]
