# Generated by Django 5.2.12 on 2026-03-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_domain'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='courses', to='departments.department'),
        ),
    ]
